name: cd

env:
  API_PORT: ${{ secrets.API_PORT }}
  API_URL: ${{ secrets.API_URL }}
  CLIENT_BASE_URL: ${{ secrets.CLIENT_BASE_URL }}
  CLIENT_PORT: ${{ secrets.CLIENT_PORT }}

on:
  pull_request:
    types: [closed]
  workflow_dispatch:

jobs:
  client-build:
    if: github.event_name == 'workflow_dispatch' || github.event.pull_request.merged == true
    name: Build and Push Docker Image
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Client Image
        uses: docker/build-push-action@v4
        with:
          context: ./front
          file: ./front/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.CLIENT_REPOSITORY_NAME }}:latest
          build-args: |
            CLIENT_PORT=${{ env.CLIENT_PORT }}
            API_URL=${{ env.API_URL }}

  server-build:
    if: github.event_name == 'workflow_dispatch' || github.event.pull_request.merged == true
    name: Build and Push Docker Image
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Server Image
        uses: docker/build-push-action@v4
        with:
          context: ./back
          file: ./back/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.SERVER_REPOSITORY_NAME }}:latest
          build-args: |
            API_PORT=${{ env.API_PORT }}
            CLIENT_BASE_URL=${{ env.CLIENT_BASE_URL }}
        
  deploy:
    if: github.event_name == 'workflow_dispatch' || github.event.pull_request.merged == true
    name: Deploy using Docker
    runs-on: ubuntu-latest
    needs: [client-build, server-build]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install SSH keys
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.REMOTE_HOST }} > ~/.ssh/known_hosts

      - name: Copy docker-compose file
        run: |
          rsync -avz -e "ssh -o StrictHostKeyChecking=no" \
          ./docker-compose.prod.yaml \
          ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:${{ secrets.PATH_TO_PROJECT }}/docker-compose.yml

      - name: Create .env file and set environment variables
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} << 'EOF'
          cd ${{ secrets.PATH_TO_PROJECT }}
          cat << 'ENV_EOF' > .env
          API_PORT=${{ env.API_PORT }}
          API_URL=${{ env.API_URL }}
          CLIENT_BASE_URL=${{ env.CLIENT_BASE_URL }}
          CLIENT_PORT=${{ env.CLIENT_PORT }}
          CLIENT_DOCKER_IMAGE=${{ secrets.DOCKER_USERNAME }}/${{ secrets.CLIENT_REPOSITORY_NAME }}:latest
          SERVER_DOCKER_IMAGE=${{ secrets.DOCKER_USERNAME }}/${{ secrets.SERVER_REPOSITORY_NAME }}:latest
          ENV_EOF
          EOF

      - name: Deploy to production
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} << 'EOF'
            cd ${{ secrets.PATH_TO_PROJECT }}
            chmod 600 .env

            docker compose -f docker-compose.yml pull
            docker compose -f docker-compose.yml up -d

            docker system prune -f -a
          EOF